//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Pull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.Students = new HashSet<Student>();
        }
    
        public short SCHOOL_ID { get; set; }
        public Nullable<short> SCHOOLLIST_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> INVOICE { get; set; }
        public string PAYMENT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string YEAR { get; set; }
    
        public virtual SchoolList SchoolList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}
