//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Pull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long STUDENT_ID { get; set; }
        public Nullable<short> SCHOOL_ID { get; set; }
        public Nullable<short> COMPETITION_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string COACH { get; set; }
        public string TYPE { get; set; }
        public string TSHIRT_SIZE { get; set; }
        public string GRADE { get; set; }
        public Nullable<short> LEVEL_ID { get; set; }
        public Nullable<short> COMPUTERPROGRAM_ID { get; set; }
        public string FINAL { get; set; }
        public string AWARD { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string YEAR { get; set; }
        public string COACHEMAIL { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual CompetitionLevel CompetitionLevel { get; set; }
        public virtual ComputerProgram ComputerProgram { get; set; }
        public virtual LiabilityForm LiabilityForm { get; set; }
        public virtual School School { get; set; }
    }
}
